# Generated by Django 4.2.2 on 2023-08-04 17:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Strategy'), ('I', 'Indicator')], default='S', max_length=1)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tradingview_ID', models.CharField(max_length=100)),
                ('tradingview_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('settings', models.JSONField(default=dict)),
                ('settings_types', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('test_start_at', models.DateTimeField()),
                ('test_end_at', models.DateTimeField()),
                ('time_frame_int', models.IntegerField(default=1)),
                ('time_frame', models.CharField(choices=[('S', 'Seconds'), ('M', 'Minutes'), ('H', 'Hours'), ('W', 'Weeks'), ('Mn', 'Months'), ('R', 'Range')], default='M', max_length=2)),
                ('pair', models.CharField(max_length=100)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_drawdown_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_factor', models.DecimalField(decimal_places=5, max_digits=12)),
                ('profitable_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_trade', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='strategies_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
        ),
    ]
