# Generated by Django 4.2.2 on 2023-08-19 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import strategies.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycomments',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategycomments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='negative_votes',
            field=models.ManyToManyField(blank=True, related_name='negative_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='positive_votes',
            field=models.ManyToManyField(blank=True, related_name='positive_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strategycomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile'),
        ),
        migrations.AlterField(
            model_name='strategycomments',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(300, 'Comment must contain at least 300 characters')]),
        ),
        migrations.AlterField(
            model_name='strategyimages',
            name='img',
            field=models.ImageField(upload_to=strategies.models.StrategyImages.photo_path),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile'),
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Comment must contain at least 100 characters')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile')),
            ],
        ),
    ]
