# Generated by Django 4.2.2 on 2023-08-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategycomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile'),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile'),
        ),
    ]
