# Generated by Django 4.2.2 on 2023-08-03 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_strategy_tradingview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='settings_data_type',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='version',
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
