# Generated by Django 4.2.2 on 2023-08-21 15:42

from django.db import migrations
import strategies.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_strategycomments_dislike_strategycomments_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='settings_types',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settings',
            field=strategies.models.SettingsJSONField(validators=[strategies.models.settings_validator_json]),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='settings',
            field=strategies.models.SettingsJSONField(validators=[strategies.models.settings_validator_json]),
        ),
    ]
