# Generated by Django 4.2.2 on 2023-12-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_remove_strategy_settings_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='broker',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss_percentage_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss_percentage_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_loss_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit_percentage_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit_percentage_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='gross_profit_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='initial_capital',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='losing_total_trade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='losing_total_trade_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='losing_total_trade_short',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='net_profit_long',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='net_profit_percentage_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='net_profit_percentage_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='net_profit_short',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='profit_factor_long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='profit_factor_short',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='profitable_percentage_long',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='profitable_percentage_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='total_trade_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='total_trade_short',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='winning_total_trade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='winning_total_trade_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='winning_total_trade_short',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='max_drawdown_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='net_profit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='net_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='pair',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='profit_factor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='profitable_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='time_frame',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years'), ('range', 'Range')], default='minutes', max_length=8),
        ),
        migrations.AlterField(
            model_name='strategyresults',
            name='total_trade',
            field=models.IntegerField(default=0),
        ),
    ]
