# Generated by Django 4.2.2 on 2023-08-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_settings_data_type_strategy_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='settings_data_type',
        ),
        migrations.AddField(
            model_name='strategy',
            name='settings',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='strategy',
            name='settings_types',
            field=models.JSONField(default=None),
        ),
    ]
