# Generated by Django 4.2.2 on 2023-08-14 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategycomments',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Comment must contain at least 100 characters')]),
        ),
    ]
