# Generated by Django 4.2.2 on 2023-08-15 15:57

import django.core.validators
from django.db import migrations, models
import strategies.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_alter_strategycomments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Comment must contain at least 100 characters')]),
        ),
        migrations.AlterField(
            model_name='strategyimages',
            name='img',
            field=models.ImageField(upload_to=strategies.models.StrategyImages.photo_path),
        ),
    ]
