# Generated by Django 4.2.2 on 2023-08-03 15:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_remove_strategy_settings_data_type_strategy_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settings',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settings_types',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
