# Generated by Django 4.2.2 on 2023-08-04 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0005_strategy_content_alter_strategy_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settings_types',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='StrategyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('test_start_at', models.DateTimeField()),
                ('test_end_at', models.DateTimeField()),
                ('time_frame_int', models.IntegerField(default=1)),
                ('time_frame', models.CharField(choices=[('S', 'Seconds'), ('M', 'Minutes'), ('H', 'Hours'), ('W', 'Weeks'), ('Mn', 'Months'), ('R', 'Range')], default='M', max_length=2)),
                ('pair', models.CharField(max_length=100)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=2)),
                ('net_profit_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=2)),
                ('max_drawdown_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('profit_factor', models.DecimalField(decimal_places=5, max_digits=5)),
                ('profitable_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('total_trade', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagees', models.ManyToManyField(to='strategies.strategyimages')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagees', models.ManyToManyField(to='strategies.strategyimages')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='results',
            field=models.ManyToManyField(to='strategies.strategyresults'),
        ),
    ]
