# Generated by Django 4.2.2 on 2024-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_strategy_chart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
