# Generated by Django 4.2.2 on 2023-08-17 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0005_alter_replies_description_alter_strategyimages_img'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='strategyresults',
        #     name='votes',
        # ),
        migrations.AddField(
            model_name='strategycomments',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategycomments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='negative_votes',
            field=models.ManyToManyField(blank=True, related_name='negative_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='positive_votes',
            field=models.ManyToManyField(blank=True, related_name='positive_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strategycomments',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(300, 'Comment must contain at least 300 characters')]),
        ),
        migrations.AddConstraint(
            model_name='strategyresults',
            constraint=models.UniqueConstraint(fields=('strategy', 'positive_votes'), name='unique_positive_votes'),
        ),
        migrations.AddConstraint(
            model_name='strategyresults',
            constraint=models.UniqueConstraint(fields=('strategy', 'negative_votes'), name='unique_negative_votes'),
        ),
    ]
