# Generated by Django 4.2.2 on 2024-02-15 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0008_strategy_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
