# Generated by Django 4.2.10 on 2024-03-04 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_strategy_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
