# Generated by Django 4.2.10 on 2024-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_strategy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
