# Generated by Django 4.2.10 on 2024-12-09 20:20

from django.db import migrations
import strategies.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_strategyresults_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='performance',
            field=strategies.models.PerferenceJSONField(default='{}', validators=[strategies.models.performance_validator_json]),
        ),
    ]
