# Generated by Django 4.2.10 on 2025-04-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0014_remove_strategyresults_gross_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='view_count',
        ),
    ]
