# Generated by Django 4.2.10 on 2025-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0015_remove_strategy_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='prumium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='short_video_url',
            field=models.URLField(blank=True),
        ),
    ]
