# Generated by Django 4.2.10 on 2025-04-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0016_strategy_prumium_strategy_short_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='prumium',
            new_name='premium',
        ),
    ]
