# Generated by Django 4.2.10 on 2025-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0017_rename_prumium_strategy_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='list_of_trades',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
