# Generated by Django 4.2.10 on 2025-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0018_strategyresults_list_of_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='premium',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Beta', 'Beta'), ('VIP', 'VIP')], default='Premium', max_length=10),
        ),
    ]
