# Generated by Django 4.2.10 on 2026-01-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0019_alter_strategy_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
