# Generated by Django 4.2.10 on 2026-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0021_remove_strategy_additional_info_strategyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyprice',
            name='interval',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='month', max_length=10),
        ),
    ]
