# Generated by Django 4.2.10 on 2026-02-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0019_user_profile_amount_to_pay'),
        ('strategies', '0022_alter_strategyprice_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='strategies.strategy')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='profile_user.user_profile')),
            ],
            options={
                'unique_together': {('strategy', 'user_profile')},
            },
        ),
    ]
