# Generated by Django 4.2.10 on 2026-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0023_strategysubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysubscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
