# Generated by Django 4.2.10 on 2024-11-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_user', '0009_alter_user_profile_lifetime_intent_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=12)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('side', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('trade_type', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('O', 'OPEN'), ('P', 'PARTIALLY_CLOSED'), ('C', 'CLOSED')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Error'), ('S', 'Success')], max_length=1)),
                ('alert_message', models.TextField()),
                ('response_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='automate.tradedetails')),
            ],
        ),
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Spot'), ('U', 'USD@M'), ('C', 'COIN@M')], default='S', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('apiKey', models.CharField(max_length=150)),
                ('secretKey', models.CharField(max_length=150)),
                ('default_symbol', models.CharField(default='', max_length=30)),
                ('default_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile')),
            ],
        ),
    ]
