# Generated by Django 4.2.10 on 2024-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binanceaccount',
            name='custom_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
