# Generated by Django 4.2.10 on 2024-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0004_cryptobrokeraccount_delete_binanceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoLogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('E', 'Error'), ('S', 'Success')], max_length=1)),
                ('alert_message', models.TextField()),
                ('response_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=12)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remaining_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('side', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('trade_type', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('O', 'OPEN'), ('P', 'PARTIALLY_CLOSED'), ('C', 'CLOSED')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tradedetails',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cryptobrokeraccount',
            name='default_volume',
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='TradeDetails',
        ),
        migrations.AddField(
            model_name='cryptotradedetails',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MAccount', to='automate.cryptobrokeraccount'),
        ),
        migrations.AddField(
            model_name='cryptologmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='automate.cryptobrokeraccount'),
        ),
        migrations.AddField(
            model_name='cryptologmessage',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trade', to='automate.cryptotradedetails'),
        ),
    ]
