# Generated by Django 4.2.10 on 2024-11-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0005_cryptologmessage_cryptotradedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotradedetails',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptotradedetails',
            name='exit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptologmessage',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trade', to='automate.cryptotradedetails'),
        ),
        migrations.AlterField(
            model_name='cryptotradedetails',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CryptoAccount', to='automate.cryptobrokeraccount'),
        ),
        migrations.AlterField(
            model_name='cryptotradedetails',
            name='trade_type',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
