# Generated by Django 4.2.10 on 2024-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0007_cryptotradedetails_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart')], max_length=20),
        ),
    ]
