# Generated by Django 4.2.10 on 2024-12-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_user_profile_lifetime_intent_and_more'),
        ('automate', '0008_alter_cryptobrokeraccount_broker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexBrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_type', models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader', 'Metatrader'), ('dxtrade', 'DXTrade')], max_length=20)),
                ('type', models.CharField(choices=[('D', 'Demo'), ('L', 'Live')], default='D', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
                ('server', models.CharField(max_length=150)),
                ('custom_id', models.CharField(default='', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.user_profile')),
            ],
        ),
    ]
