# Generated by Django 4.2.10 on 2024-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0010_logmessage_tradedetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('dxtrade', 'DXTrade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='entry_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='exit_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='remaining_volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
