# Generated by Django 4.2.10 on 2025-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0011_alter_forexbrokeraccount_broker_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptobrokeraccount',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='type',
            field=models.CharField(choices=[('D', 'Derivatives'), ('F', 'Futures'), ('S', 'Spot'), ('U', 'USD@M'), ('C', 'COIN@M'), ('UC', 'USD@C')], default='S', max_length=2),
        ),
    ]
