# Generated by Django 4.2.10 on 2025-02-07 16:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0012_cryptobrokeraccount_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='secretKey',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=150)),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=150)),
        ),
    ]
