# Generated by Django 4.2.10 on 2025-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0014_alter_logmessage_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetails',
            name='custom_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='order_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='symbol',
            field=models.CharField(max_length=24),
        ),
    ]
