# Generated by Django 4.2.10 on 2025-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0016_alter_tradedetails_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='account_api_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart'), ('crypto', 'Crypto.com')], max_length=20),
        ),
    ]
