# Generated by Django 4.2.10 on 2025-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0017_forexbrokeraccount_account_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='subscription_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='subscription_id',
            field=models.CharField(max_length=100),
        ),
    ]
