# Generated by Django 4.2.10 on 2025-05-06 20:46

import automate.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0018_alter_cryptobrokeraccount_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='fees',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='fills',
            field=models.JSONField(blank=True, default=list, validators=[automate.models.validate_fills]),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='custom_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='entry_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='exit_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='order_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='profit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='remaining_volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='symbol',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
