# Generated by Django 4.2.10 on 2025-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0019_tradedetails_entry_time_tradedetails_exit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
    ]
