# Generated by Django 4.2.10 on 2025-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0020_tradedetails_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='closed_order_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
