# Generated by Django 4.2.10 on 2025-05-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0018_strategyresults_list_of_trades'),
        ('automate', '0021_tradedetails_closed_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='strategies.strategy'),
        ),
    ]
