# Generated by Django 4.2.10 on 2025-06-14 19:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0022_tradedetails_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='apiKey',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart'), ('crypto', 'Crypto.com'), ('kucoin', 'Kucoin'), ('okx', 'Okx'), ('coinbase', 'Coinbase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='secretKey',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=350)),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='type',
            field=models.CharField(choices=[('D', 'Derivatives'), ('P', 'Perps'), ('F', 'Futures'), ('S', 'Spot'), ('U', 'USD@M'), ('C', 'COIN@M'), ('UC', 'USD@C')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='account_api_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('tradestation', 'TradeStation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='custom_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
