# Generated by Django 4.2.10 on 2025-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0023_alter_cryptobrokeraccount_apikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptobrokeraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
