# Generated by Django 4.2.10 on 2025-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0024_cryptobrokeraccount_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='latency',
            field=models.FloatField(blank=True, default=0.0, help_text='Latency in seconds'),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart'), ('crypto', 'Crypto.com'), ('kucoin', 'Kucoin'), ('okx', 'Okx'), ('coinbase', 'Coinbase'), ('apex', 'Apex omni')], max_length=20),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('ctrader', 'CTrader'), ('tradestation', 'TradeStation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='trade_type',
            field=models.CharField(default='S', max_length=2),
        ),
    ]
