# Generated by Django 4.2.10 on 2025-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0025_logmessage_latency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='trade_latency',
            field=models.FloatField(blank=True, default=0.0, help_text='Trade Latency in seconds'),
        ),
    ]
