# Generated by Django 4.2.10 on 2025-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0026_logmessage_trade_latency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('ctrader', 'CTrader'), ('hankotrade', 'HankoTrade'), ('tradestation', 'TradeStation')], max_length=20),
        ),
    ]
