# Generated by Django 4.2.10 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0027_alter_forexbrokeraccount_broker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='pass_phrase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
