# Generated by Django 4.2.10 on 2025-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0028_alter_cryptobrokeraccount_pass_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptobrokeraccount',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('binanceus', 'Binance US'), ('bitget', 'Bitget'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('bingx', 'Bingx'), ('bitmex', 'Bitmex'), ('bitmart', 'BitMart'), ('crypto', 'Crypto.com'), ('kucoin', 'Kucoin'), ('kraken', 'Kraken'), ('okx', 'Okx'), ('coinbase', 'Coinbase'), ('apex', 'Apex omni'), ('hyperliquid', 'Hyperliquid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('ctrader', 'CTrader'), ('hankotrade', 'HankoTrade'), ('tradestation', 'TradeStation'), ('alpaca', 'Alpaca')], max_length=20),
        ),
    ]
