# Generated by Django 4.2.10 on 2025-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0029_cryptobrokeraccount_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('ctrader', 'CTrader'), ('hankotrade', 'HankoTrade'), ('tradestation', 'TradeStation'), ('alpaca', 'Alpaca'), ('tastytrade', 'Tastytrade')], max_length=20),
        ),
    ]
