# Generated by Django 4.2.10 on 2025-12-12 18:07

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0030_tradedetails_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='custom_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='cryptobrokeraccount',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='account_api_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='broker_type',
            field=models.CharField(choices=[('tradelocker', 'TradeLocker'), ('metatrader4', 'Metatrader 4'), ('metatrader5', 'Metatrader 5'), ('ninjatrader', 'NinjaTrader'), ('dxtrade', 'DXTrade'), ('ctrader', 'CTrader'), ('deriv', 'Deriv'), ('hankotrade', 'HankoTrade'), ('tradestation', 'TradeStation'), ('alpaca', 'Alpaca'), ('tastytrade', 'Tastytrade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='custom_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=600)),
        ),
        migrations.AlterField(
            model_name='forexbrokeraccount',
            name='username',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='response_status',
            field=models.CharField(choices=[('E', 'Error'), ('S', 'Success'), ('I', 'Info'), ('W', 'Warning')], max_length=1),
        ),
    ]
