# Generated by Django 4.2.10 on 2025-12-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0031_alter_cryptobrokeraccount_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptobrokeraccount',
            name='performance_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cryptobrokeraccount',
            name='public_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='performance_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forexbrokeraccount',
            name='public_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
