# Generated by Django 4.2.10 on 2025-12-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('strategies', '0018_strategyresults_list_of_trades'),
        ('automate', '0032_cryptobrokeraccount_performance_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('asset', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_performances', to='automate.accountperformance')),
            ],
        ),
        migrations.CreateModel(
            name='DayAssetPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate.assetperformance')),
            ],
        ),
        migrations.CreateModel(
            name='DayPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_performances', to='automate.accountperformance')),
                ('assets', models.ManyToManyField(related_name='day_performances', through='automate.DayAssetPerformance', to='automate.assetperformance')),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptobrokeraccount',
            name='performance_data',
        ),
        migrations.RemoveField(
            model_name='forexbrokeraccount',
            name='performance_data',
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_performances', to='automate.accountperformance')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCurrencyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('total_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('strategy_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='automate.strategyperformance')),
            ],
        ),
        migrations.CreateModel(
            name='DayStrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate.dayperformance')),
                ('strategy_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate.strategyperformance')),
            ],
        ),
        migrations.AddField(
            model_name='dayperformance',
            name='strategies',
            field=models.ManyToManyField(related_name='day_performances', through='automate.DayStrategyPerformance', to='automate.strategyperformance'),
        ),
        migrations.CreateModel(
            name='DayCurrencyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('total_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('day_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='automate.dayperformance')),
            ],
        ),
        migrations.AddField(
            model_name='dayassetperformance',
            name='day_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate.dayperformance'),
        ),
        migrations.CreateModel(
            name='AssetCurrencyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('total_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('asset_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='automate.assetperformance')),
            ],
        ),
        migrations.CreateModel(
            name='AccountCurrencyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('total_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('account_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='automate.accountperformance')),
            ],
        ),
        migrations.CreateModel(
            name='TradeAppliedPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_type', models.CharField(max_length=32)),
                ('performance_id', models.PositiveBigIntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_performances', to='automate.tradedetails')),
            ],
            options={
                'indexes': [models.Index(fields=['trade'], name='automate_tr_trade_i_4bdb2e_idx'), models.Index(fields=['performance_type', 'performance_id'], name='automate_tr_perform_9457f7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tradeappliedperformance',
            constraint=models.UniqueConstraint(fields=('trade', 'performance_type', 'performance_id'), name='unique_trade_performance_application_v2'),
        ),
        migrations.AddConstraint(
            model_name='strategyperformance',
            constraint=models.UniqueConstraint(fields=('account_performance', 'strategy'), name='unique_strategy_per_account'),
        ),
        migrations.AddConstraint(
            model_name='strategycurrencyperformance',
            constraint=models.UniqueConstraint(fields=('strategy_performance', 'currency'), name='unique_strategy_currency'),
        ),
        migrations.AddIndex(
            model_name='daystrategyperformance',
            index=models.Index(fields=['day_performance'], name='automate_da_day_per_1183fa_idx'),
        ),
        migrations.AddIndex(
            model_name='daystrategyperformance',
            index=models.Index(fields=['strategy_performance'], name='automate_da_strateg_f4df72_idx'),
        ),
        migrations.AddConstraint(
            model_name='daystrategyperformance',
            constraint=models.UniqueConstraint(fields=('day_performance', 'strategy_performance'), name='unique_strategy_per_day'),
        ),
        migrations.AddIndex(
            model_name='dayperformance',
            index=models.Index(fields=['account_performance', 'date'], name='automate_da_account_274395_idx'),
        ),
        migrations.AddIndex(
            model_name='dayperformance',
            index=models.Index(fields=['date'], name='automate_da_date_b4fbb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayperformance',
            constraint=models.UniqueConstraint(fields=('account_performance', 'date'), name='unique_day_per_account'),
        ),
        migrations.AddConstraint(
            model_name='daycurrencyperformance',
            constraint=models.UniqueConstraint(fields=('day_performance', 'currency'), name='unique_day_currency'),
        ),
        migrations.AddIndex(
            model_name='dayassetperformance',
            index=models.Index(fields=['day_performance'], name='automate_da_day_per_aaab21_idx'),
        ),
        migrations.AddIndex(
            model_name='dayassetperformance',
            index=models.Index(fields=['asset_performance'], name='automate_da_asset_p_edb9a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayassetperformance',
            constraint=models.UniqueConstraint(fields=('day_performance', 'asset_performance'), name='unique_asset_per_day'),
        ),
        migrations.AddIndex(
            model_name='assetperformance',
            index=models.Index(fields=['account_performance', 'asset'], name='automate_as_account_efb078_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetperformance',
            constraint=models.UniqueConstraint(fields=('account_performance', 'asset'), name='unique_asset_per_account'),
        ),
        migrations.AddConstraint(
            model_name='assetcurrencyperformance',
            constraint=models.UniqueConstraint(fields=('asset_performance', 'currency'), name='unique_asset_currency'),
        ),
        migrations.AddIndex(
            model_name='accountperformance',
            index=models.Index(fields=['content_type', 'object_id'], name='automate_ac_content_280cf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountperformance',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_account_performance'),
        ),
        migrations.AddConstraint(
            model_name='accountcurrencyperformance',
            constraint=models.UniqueConstraint(fields=('account_performance', 'currency'), name='unique_account_currency'),
        ),
    ]
