# Generated by Django 4.2.10 on 2025-12-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('automate', '0033_accountperformance_assetperformance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetails',
            name='net_profit',
        ),
        migrations.AlterField(
            model_name='accountperformance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_performances', to='contenttypes.contenttype'),
        ),
    ]
