# Generated by Django 4.2.10 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0036_rename_total_fees_accountcurrencyperformance_buy_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcurrencyperformance',
            old_name='buy_fees',
            new_name='buy_losing_fees',
        ),
        migrations.RenameField(
            model_name='accountcurrencyperformance',
            old_name='buy_profit',
            new_name='buy_losing_net_profit',
        ),
        migrations.RenameField(
            model_name='accountcurrencyperformance',
            old_name='sell_fees',
            new_name='buy_winning_fees',
        ),
        migrations.RenameField(
            model_name='accountcurrencyperformance',
            old_name='sell_profit',
            new_name='buy_winning_net_profit',
        ),
        migrations.RenameField(
            model_name='assetcurrencyperformance',
            old_name='buy_fees',
            new_name='buy_losing_fees',
        ),
        migrations.RenameField(
            model_name='assetcurrencyperformance',
            old_name='buy_profit',
            new_name='buy_losing_net_profit',
        ),
        migrations.RenameField(
            model_name='assetcurrencyperformance',
            old_name='sell_fees',
            new_name='buy_winning_fees',
        ),
        migrations.RenameField(
            model_name='assetcurrencyperformance',
            old_name='sell_profit',
            new_name='buy_winning_net_profit',
        ),
        migrations.RenameField(
            model_name='daycurrencyperformance',
            old_name='buy_fees',
            new_name='buy_losing_fees',
        ),
        migrations.RenameField(
            model_name='daycurrencyperformance',
            old_name='buy_profit',
            new_name='buy_losing_net_profit',
        ),
        migrations.RenameField(
            model_name='daycurrencyperformance',
            old_name='sell_fees',
            new_name='buy_winning_fees',
        ),
        migrations.RenameField(
            model_name='daycurrencyperformance',
            old_name='sell_profit',
            new_name='buy_winning_net_profit',
        ),
        migrations.RenameField(
            model_name='strategycurrencyperformance',
            old_name='buy_fees',
            new_name='buy_losing_fees',
        ),
        migrations.RenameField(
            model_name='strategycurrencyperformance',
            old_name='buy_profit',
            new_name='buy_losing_net_profit',
        ),
        migrations.RenameField(
            model_name='strategycurrencyperformance',
            old_name='sell_fees',
            new_name='buy_winning_fees',
        ),
        migrations.RenameField(
            model_name='strategycurrencyperformance',
            old_name='sell_profit',
            new_name='buy_winning_net_profit',
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='largest_buy_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='largest_buy_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='largest_sell_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='largest_sell_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='sell_losing_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='sell_losing_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='sell_winning_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='accountcurrencyperformance',
            name='sell_winning_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='largest_buy_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='largest_buy_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='largest_sell_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='largest_sell_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='sell_losing_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='sell_losing_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='sell_winning_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='assetcurrencyperformance',
            name='sell_winning_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='largest_buy_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='largest_buy_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='largest_sell_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='largest_sell_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='sell_losing_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='sell_losing_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='sell_winning_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='daycurrencyperformance',
            name='sell_winning_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='largest_buy_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='largest_buy_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='largest_sell_net_loss',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='largest_sell_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='sell_losing_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='sell_losing_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='sell_winning_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='strategycurrencyperformance',
            name='sell_winning_net_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
