# Generated by Django 4.2.10 on 2026-01-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0037_rename_buy_fees_accountcurrencyperformance_buy_losing_fees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCurrencyPerformance',
        ),
        migrations.DeleteModel(
            name='AccountPerformance',
        ),
        migrations.DeleteModel(
            name='AssetCurrencyPerformance',
        ),
        migrations.DeleteModel(
            name='AssetPerformance',
        ),
        migrations.DeleteModel(
            name='DayAssetPerformance',
        ),
        migrations.DeleteModel(
            name='DayCurrencyPerformance',
        ),
        migrations.DeleteModel(
            name='DayPerformance',
        ),
        migrations.DeleteModel(
            name='DayStrategyPerformance',
        ),
        migrations.DeleteModel(
            name='StrategyCurrencyPerformance',
        ),
        migrations.DeleteModel(
            name='StrategyPerformance',
        ),
        migrations.DeleteModel(
            name='TradeAppliedPerformance',
        ),
    ]
