# Generated by Django 4.2.10 on 2026-01-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAssetStrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_strategy_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_performances', to='performance.assetstrategyperformance')),
                ('day_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_asset_strategies', to='performance.dayperformance')),
            ],
        ),
        migrations.CreateModel(
            name='DayAssetStrategyCurrencyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_total_trades', models.PositiveIntegerField(default=0)),
                ('buy_winning_trades', models.PositiveIntegerField(default=0)),
                ('buy_losing_trades', models.PositiveIntegerField(default=0)),
                ('sell_total_trades', models.PositiveIntegerField(default=0)),
                ('sell_winning_trades', models.PositiveIntegerField(default=0)),
                ('sell_losing_trades', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('buy_winning_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('sell_winning_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('buy_winning_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('sell_winning_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('buy_losing_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('sell_losing_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('buy_losing_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('sell_losing_fees', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('largest_buy_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('largest_sell_net_profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('largest_buy_net_loss', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('largest_sell_net_loss', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('day_asset_strategy_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='performance.dayassetstrategyperformance')),
            ],
        ),
        migrations.AddIndex(
            model_name='dayassetstrategyperformance',
            index=models.Index(fields=['day_performance'], name='performance_day_per_76e217_idx'),
        ),
        migrations.AddIndex(
            model_name='dayassetstrategyperformance',
            index=models.Index(fields=['asset_strategy_performance'], name='performance_asset_s_76201b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayassetstrategyperformance',
            constraint=models.UniqueConstraint(fields=('day_performance', 'asset_strategy_performance'), name='unique_asset_strategy_per_day'),
        ),
        migrations.AddConstraint(
            model_name='dayassetstrategycurrencyperformance',
            constraint=models.UniqueConstraint(fields=('day_asset_strategy_performance', 'currency'), name='unique_day_asset_strategy_currency'),
        ),
    ]
