# Generated by Django 4.2.10 on 2026-01-14 07:14

from django.db import migrations, models
import django.db.models.deletion


def remove_duplicates(apps, schema_editor):
    TradeAppliedPerformance = apps.get_model('performance', 'TradeAppliedPerformance')
    seen = set()
    duplicates = []
    
    for tap in TradeAppliedPerformance.objects.all().order_by('id'):
        key = (tap.trade_id, tap.content_type_id, tap.object_id)
        if key in seen:
            duplicates.append(tap.id)
        else:
            seen.add(key)
    
    TradeAppliedPerformance.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('performance', '0002_add_day_asset_strategy_performance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradeappliedperformance',
            name='unique_trade_performance_application_v2',
        ),
        migrations.RemoveIndex(
            model_name='tradeappliedperformance',
            name='performance_perform_be8743_idx',
        ),
        migrations.RemoveField(
            model_name='tradeappliedperformance',
            name='performance_id',
        ),
        migrations.RemoveField(
            model_name='tradeappliedperformance',
            name='performance_type',
        ),
        migrations.AddField(
            model_name='tradeappliedperformance',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeappliedperformance',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: remove_duplicates(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='tradeappliedperformance',
            index=models.Index(fields=['content_type', 'object_id'], name='performance_content_14335b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradeappliedperformance',
            constraint=models.UniqueConstraint(fields=('trade', 'content_type', 'object_id'), name='unique_trade_performance_application_v2'),
        ),
    ]
