# Generated by Django 4.2.10 on 2025-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saro', '0002_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_used',
            field=models.IntegerField(default=0),
        ),
    ]
