# Generated by Django 4.2.10 on 2025-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saro', '0003_chatmessage_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
