# Generated by Django 4.2.10 on 2025-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tero', '0004_chatsession_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='embedding',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='raw_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
