# Generated by Django 4.2.10 on 2025-09-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tero', '0005_remove_chatmessage_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='raw_state',
            new_name='summary_state',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='last_version',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='summary',
        ),
    ]
