# Generated by Django 4.2.10 on 2026-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tero', '0006_rename_raw_state_chatsession_summary_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
