# Generated by Django 4.2.10 on 2026-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tero', '0007_chatsession_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
