# Generated by Django 4.2.2 on 2024-01-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_lifetime',
            field=models.BooleanField(default=False),
        ),
    ]
