# Generated by Django 4.2.2 on 2024-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_user_profile_is_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='lifetime_intent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
