# Generated by Django 4.2.2 on 2024-01-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_user_profile_lifetime_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='lifetime_num',
            field=models.IntegerField(default=0),
        ),
    ]
