# Generated by Django 4.2.2 on 2024-02-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_strategy_likes'),
        ('profile_user', '0004_user_profile_lifetime_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='strategies',
            field=models.ManyToManyField(blank=True, to='strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
