# Generated by Django 4.2.2 on 2024-02-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
