# Generated by Django 4.2.10 on 2024-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0008_alter_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='lifetime_intent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tradingview_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
