# Generated by Django 4.2.10 on 2025-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_user_profile_lifetime_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='discord_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
