# Generated by Django 4.2.10 on 2025-02-17 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_user_profile_lifetime_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='ai_tokens_used_today',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_token_reset',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
