# Generated by Django 4.2.10 on 2025-02-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0010_user_profile_ai_tokens_used_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='ai_tokens_available',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
