# Generated by Django 4.2.10 on 2025-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0011_user_profile_ai_tokens_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='has_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='stripe_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='stripe_obj',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
