# Generated by Django 4.2.10 on 2025-04-28 03:58

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0012_user_profile_has_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='stripe_obj',
            field=models.JSONField(blank=True, encoder=profile_user.models.PrettyJSONEncoder, null=True),
        ),
    ]
