# Generated by Django 4.2.10 on 2025-07-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0013_alter_user_profile_stripe_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='ai_tokens_used_today',
            new_name='ai_free_daily_tokens_available',
        ),
    ]
