# Generated by Django 4.2.10 on 2025-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0014_rename_ai_tokens_used_today_user_profile_ai_free_daily_tokens_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='automate_free_access',
            field=models.BooleanField(default=False),
        ),
    ]
