# Generated by Django 4.2.10 on 2025-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0015_user_profile_automate_free_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='automate_free_access',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='automate_access',
            field=models.CharField(default='', max_length=100),
        ),
    ]
