# Generated by Django 4.2.10 on 2026-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0017_user_profile_seller_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True),
        ),
    ]
