# Generated by Django 4.2.10 on 2026-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0018_user_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
