# Generated by Django 4.2.10 on 2026-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0019_user_profile_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='ISO 639-1 language code', max_length=10, null=True),
        ),
    ]
